select * from details;
update details set department="cse" where id=1;
update details set department="eee" where id=2;
update details set department="mca" where id=3;
update details set department="mech" where id=4;
update details set department="ece" where id=5;
update details set department="cse" where id=6;
update details set department="eee" where id=7;
update details set department="cse" where id=8;
update details set department="civil" where id=9;
update details set department="mca" where id=10;
select distinct department from details;
create table department(dept_id int,dept_name varchar(15) , loc_id int);
insert into department values(100,"mca",8765);
insert into department values(101,"zoology",1235);
insert into department values(102,"commerce",8765);
insert into department values(104,"maths",3367);
select * from department;
alter table department add constraint dept_id_pk primary key (dept_id);
desc department;
select address from details union select loc_id from department;
desc details;
